import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import GrowthCard from '@/components/charts/growth_thermometer/growth_card'
import RadarCard from '@/components/charts/radar/radar_card'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const sampleDataForRadarChart={"liquidity_score":"AA","network_score":"A","price_score":"AAA"};
  
  const sampleDataForHistoryChart=[];
  return (
    <>
      <Head>
        <title>Xerberus Charts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {/* Replace the following sample data with actual data from the API when integrating into your application */}
       <GrowthCard token={'WMT'} growth_score={'Moderate'} backgroundColor={'white'} border={'white'}/>
       <br/>
       <RadarCard token={'WMT'} scoresData={sampleDataForRadarChart}/>
      </main>
    </>
  )
}
